### ISSUE TITLE
Consider leaving a constructive comment on this issue if you have applied for our Unity SDK Software Engineer position

### ISSUE THREAD

**Issue by matt-manuel** [CognitiveVR/cvr-sdk-unity#93]
[Software Engineer - Unity SDK](https://www.linkedin.com/jobs/view/3711669241/)

To comment non-publicly you can find me on LinkedIn or email me at my first name at the company URL.

**Comment by The-NinToaster** [comment]
Hi! I am Nikki Babaii, and I took a look around this repo. Very cool toolkit. Tried to run the demo scene on my instance of unity, running into some build issues on my end. Regardless, looked at the offerings on the dashboard and they're very interesting, specially for gaming insights such as performance. Very interested in the direction of the project. 
I wonder if later we can get insights on eye lines (where they see), hotspots (places where many have gathered and for how long). I see this being quite useful for games like VRChat or for VR Showrooms such as the ones Rove Concepts developed. 
I see that AR is also within your focus. I wonder if it can expand to AR gaming, such as Pokemon Go, Monster Hunter Now, etc. 
In any case, this is very cool and even if i don't join the team, I'm excited to see where this will go.
My LinkedIn is Nikki Babaii.

**Comment by Phinieo** [comment]
I'm very impressed by the variety of hardware this SDK supports! The two critiques that jump to mind after a cursory look over the commit history and documentation are a lack of support for custom VR/AR setups and the latest MRTK version. From what I could see, the setup has support for MRTK 2.5.4 while the latest, and what I've been working with is 2.8.3. Following the release of Apple's Vision Pro AR headset, I expect the AR industry to boom, including Microsoft's Hololens line, which runs on MRTK. Updated MRTK support could become a core part of Cognitive3D's use cases. Besides this, looking at this SDK made me think about its implementation into custom-engineered VR setups, particularly large parallel computing systems such as a CAVE. The current implementation of the SDK's function calls for logging data may not mesh particularly well with Unity software components such as MiddleVR that manage distributing inputs, randomization, and graphics processing between several cluster nodes.

**Comment by Mourud** [comment]
## Constructive Feedback on Unity SDK Software Engineer Application Process and Tool Experience

Hello Team,

I recently applied for the Unity SDK Software Engineer position and have some suggestions for improvement after fiddling with the app for a while:

### 1. **Network Error on Dashboard**
- During the initial setup, controllers failed to load in the viewer on the dashboard, displaying a "Network Error."
- Suggestion: I suspect the issue may be related to the object not having a renderer. When I added a controller that did have a renderer, the error was resolved. This leads me to think that the problem could be tied to renderer absence. A more descriptive error message could help users troubleshoot this issue more effectively.

### 2. **Screenshot Download**
- Screenshots download from the dashboard but are not saved as media files.
- Suggestion: Clarify if this is intended or consider adding media save functionality.

### 3. **Scene Upload Functionality**
- There is an option to upload multiple scenes, but limited documentation or guidelines.
- Suggestion: Add a video tutorial or guidelines focused on multiple scene management.

### 4. **Video on scene setup window**
- Expected a scene setup guide but found a similar video to the SDK setup.
- Suggestion: Create a separate, detailed video focusing solely on scene setup.

### 5. **Dark Mode UI Theme Consistency**
- The dashboard's UI doesn't align well with Unity's dark mode theme.
- Suggestion: Implement a dark mode for the dashboard that automatically activates to match Unity's settings.

Thank you for considering my feedback.

Best,
Ishmam

**Comment by Mourud** [comment]
Hello again Team,

While going through the application process for the Unity SDK Software Engineer position, I came across a small bug related to the display of recorded sessions on the analytics dashboard. Below are the details. I hope this helps:


### System Specifications:
- **Device**: M1 MacBook Air
- **Browser**: Safari 16.5.2
- **Unity Version**: 2022.3.4f1

### Steps to Reproduce:

1. **Initialize the Unity Project**
    - Launch Unity and create a new project.
    - Choose the "Default VR Project" template.

2. **Install SDK via Unity Package Manager**
    - Navigate to `Window` > `Package Manager`.
    - Use the provided Git URL to install the SDK package.

3. **Initial SDK Setup for Analytics**
    1. Open the SDK setup wizard.
    2. Select "Default VR SDK" option.


4. **Scene Setup**
    - Completed the scene setup wizard.
    - Add one dynamic object for analytics.
    - Uploaded everything available on the window

5. **Testing and Recording**
    - Hit "Play" in Unity.
    - Attempt to record the session and upload to the analytics dashboard.

### Issues Observed:

1. Initially, the dashboard's scenes view indicated that **no sessions were recorded**.
  ![image](https://github.com/CognitiveVR/cvr-sdk-unity/assets/34059527/5e970101-173f-4e96-84a7-7a72513b750d)

2. Upon clicking into the scenes view, the **actual recorded sessions were revealed**.
  ![image](https://github.com/CognitiveVR/cvr-sdk-unity/assets/34059527/956f83bb-83e7-4857-a034-a5693dfb034a)


### Additional info:
The Project view also showed that there were sessions recorded. So the issue is only in the scene view
![image](https://github.com/CognitiveVR/cvr-sdk-unity/assets/34059527/d6ba8cb1-bdb7-4f5c-8844-3e53992bd53a)

**Comment by joeydawg7** [comment]
Hey guys, great Toolkit I can see a lot of uses for it in the VR/AR gaming space and beyond. I was especially interested in your analytics about performance and Live ops, and the way the data was presented in various useful visualizations. 

I ran into some issues most of which seemed to be related to the new Dashboard which I understand is still a work in progress. I also had an issue with the Quick Setup Video on this page https://docs.cognitive3d.com/unity/minimal-setup-guide/ where reaching the exporting objects section of the video would always cause the video to crash. Running on Windows 10 tested Firefox and Chrome with no add-ons.  The developer console showed this warning whenever the issue occurred:
“Shaka Player's internal Manifest structure is NOT covered by semantic versioning compatibility guarantees. It may change at any time! Please consider filing a feature request for whatever you use getManifest() for.”

I ran into an additional issue where renaming Scene in Unity will not update Scene Name in the Scene Settings or on the web dashboard. This also made it very hard to track which scenes I was analyzing on the dashboard.

Some General Constructive Comments / Minor issues:
-	I would like it if I could see how the Comfort, Presence, and Performance scores are calculated on the page that displays them in more detail.  Perhaps by clicking or hovering over the informational “i”?
-	When I clicked to try pro for 30 days on your website, I was surprised that there was no confirmation or additional page… I was intending to see what features Pro offered and instead, my account was instantly upgraded
-	I wanted to have the ability to completely remove a scene from being tracked in the All-Scenes dropdown from the dashboard
-	No ability to track custom events on the new dashboard (I’m assuming this will come in time)
-	Very minor issue but in the email message I got with more information about the software I was referred to as Chris null because I don’t have an inputted last name

Overall great toolkit I’m looking forward to seeing how it develops.
You can reach me on LinkedIn at https://www.linkedin.com/in/chris-lyons-a6049089/
Thanks :)

**Comment by cruzjunior** [comment]
Hi!
I currently work in developing VR mini-games and gathering user input data, that being from an HMD or just mouse and keyboard, for academic research purposes. In addition to that, I also have to develop tools to automate the process that are easy enough for the researchers to use and understand, therefore, I went into trying this SDK with my current research eyes.

The first thing I noticed is the amount of data collected at once after you’re done with the quick setup, it is quite a lot, at least for research. In research, you want to have complete control of what data is being recorded, so an easy setup to choose what we want to record would help researchers use the SDK and also keep it lightweight for whatever purpose the research is for. Too many measurements can lead to wrong conclusions. 

Also, some more transparency on how things are being calculated would definitely be needed in research. Like the comment above I was also a bit confused as to how comfort, presence, and performance scores were being calculated, maybe it is shown somewhere but I could not find it.

With the Dynamic Objects, it would be great if the user could add more data to be recorded through another script. For example, if I want to continuously record the angle between two objects and one of those objects is a dynamic object I can then just pass that value to the DynamicObject.cs script and it would aggregate to the final output for that dynamic object. I can see that BeginEngagement in DynamicManager.cs might be able to already do something like that but if I understand it correctly it is just creating a custom event, which records the x,y, and z position but it would be great if it could record other types of data that are not just position. 

Right now where I work we use UXF and it sort of does the job that we need, and although UXF does collect some information on its own, for the majority of objects we have to track and record everything ourselves and then just pass those recordings to UXF, and the SDK then formats it and outputs as a CSV file (which is trivial and we can do it ourselves, but we do use UXF for other purposes as well). This is good and bad at the same time, it is good because we then have complete control of what measurements we are tracking and it is bad because we have to develop our own automated tools that work well with UXF. In a perfect world, we would not need to create any tools ourselves and I do see this Cognitive3D SDK going in that direction and being super useful in the research field.

Best,
[Jorge de Oliveira ](https://www.linkedin.com/in/jorgedeoliveira/)

**Comment by KARNB24** [comment]
Hi,

My name is Karn Bhavsar, and I have applied for your company's Unity SDK Software Engineer position. I tried running this SDK on my version of Unity (2021.3.4f1) and the setup process was easy to understand. I started off by creating a sample VR project and adding this SDK through the package manager. It then ran through the project setup, asking for the validation key which I got through the Cognitive3D Dashboard. It was so nice to see that It supports variety of VR devices. I selected Oculus Integration as I have experience working with them. I followed the On-Screen instructions and in the end, my scene was ready to view on the dashboard. Looking at the Dashboard, it gives through details of your app, which helps the developers on how the users use it. If I get selected, I am really excited to use this SDK. 

LinkedIn: https://www.linkedin.com/in/karn-bhavsar/

Thanks,

Karn Bhavsar

**Comment by parisasargolzaei** [comment]
Hi Team,

I'm Parisa Sargolzaei and I've submitted my application for the Unity SDK Software Engineer position. I'm genuinely impressed by the capabilities of the SDK, which serves as an invaluable toolkit for users to analyze their data. It offers profound insights into project dynamics. I find Cognitive3D to be exceptionally valuable in the gaming industry.

Drawing from my research background, I have experience in developing a game analytics tool specifically tailored for Mixed Reality games, with a focus on HoloLens 2. This experience has underscored the significance of capturing and tracking hand movements in the realm of Mixed Reality (MR) applications. Hand movements are often the core mechanism in such applications. In my research, the hand tracker played a pivotal role in reconstructing the original game session from recorded game metrics, particularly in the context of a first-person shooter game where hand gestures were used as input. The hand tracker not only provided insights into user interactions but also allowed users to observe precise hand poses and gestures from the original session. I believe that incorporating this feature into the SDK could prove to be an invaluable asset.

Given the opportunity to join your team, I would be enthusiastic about sharing additional ideas on how to enhance the current SDK further.

I am genuinely excited about the prospect of becoming a part of your team and eagerly await your response.

Thanks,
Parisa
LinkedIn: https://www.linkedin.com/in/parisasargolzaei/

**Comment by zaalsabb** [comment]
Hi all,

I'm very impressed with this SDK and the talent of the team behind Cognitive3D who developed it, which is why I applied for this position!

One thing that I want to point out that really impressed me is the way that you handle multiplayer sessions. The fact that you do not rely on a centralized server and instead use the lobby id to group sessions from multiple users minimizes potential server hosting costs compared to implementing this feature using a centralized server. However, I wonder if implementing a centralized server could allow you to collect additional data about how users interact with each other, which may not be possible with just a client-side implementation.

This is a useful feature for me since I develop AR/VR collaborative applications where multiple AR and VR users are working together in the same 3D environments to perform remote bridge inspections. So, I would love to be able to collect data about how users are collaborating with each other.

[My LinkedIn](https://linkedin.com/in/zaidsabbag)

**Comment by matt-manuel** [comment]
We are about to close the job posting on LinkedIn. Thank you for your comments.
